apiVersion: v1
kind: ConfigMap
metadata:
  name: puku-config
  namespace: puku-app
data:
  POSTGRES_DB: recipe_db
  POSTGRES_USER: admin
  DATABASE_URL: postgresql://admin:password@postgres-service:5432/recipe_db
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  USER_SERVICE_URL: http://user-service:8001
  RECIPE_SERVICE_URL: http://recipe-service:8002
  RATING_SERVICE_URL: http://rating-service:8003
